title: Student Portfolio
logo: /assets/img/logo.png
description: Showcase of student projects and achievements
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

collections:
  projects:
    output: true
